dbConfig:
  endpoint: "jdbc:oracle:thin:@localhost:1521:xe"
  username: "dropwizard"
  password: "oracle"
server:
  type: simple
  adminContextPath: /admin
  applicationContextPath: /
  rootPath: /api
  connector:
    type: http
    port: 8080