startTime: 1479910400000
dbConfig:
  endpoint: "jdbc:oracle:thin:@localhost:6000:xe"
  username: "jb"
  password: "oracle"
server:
  type: simple
  adminContextPath: /admin
  applicationContextPath: /
  rootPath: /api
  connector:
    type: http
    port: 8080
